### ISSUE TITLE
Typos in BCS transformation?

### ISSUE THREAD

**Issue by cdesaintguilhem** [hash-based-snargs-book/hash-based-snargs-book#5]
Hi both,

Thank you so much for this wonderful book!

I'm wondering if there is a small typo in step 3 of the prover in Construction 25.1.1 (line 15377): should the superscript of the alphabet be the query set $Q_i$ itself, or rather the size $|Q_i|$ of that query set? (Or is this an intentional notation overload that is explained somewhere and that I missed?)

**Comment by cdesaintguilhem** [comment]
Also in the same Construction, in step 5 of the prover, should the $i \in [\mathsf{k}]$ subscript be inside the outer pair of parentheses?

**Comment by eylonyogev** [comment]
Hey Cyprien,

Thanks for the comments, these are very helpful.

Regarding the first comment, this is not a typo. It is a string of length $|Q_i|$ indexed according to the elements in $Q_i$, which makes it much easier to access (i.e., if $Q_i=\{1,8\}$ then you can access $a_i[8]$). We have revised the notation section (Section 1.1) to clarify this (see Tuples and Strings).

Regarding the second comment, it is also not a typo. This is a tuple of tuples (similar to the tuple $(\rho_i)_{i \in [k]}$ but now replace $\rho$ with a tuple). Again, take a look at the revised Section 1.1 for examples and clarifications.

Best,
Eylon.
